--------------------------------------------------------------------------------
-- Copyright (c) 1995-2007 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 9.2.04i
--  \   \         Application : xaw2vhdl
--  /   /         Filename : plldiv.vhd
-- /___/   /\     Timestamp : 01/24/2008 15:59:53
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st C:\Data\Projects\FreeFormPCI104\hardware\logic\source\v5coregen\plldiv.xaw C:\Data\Projects\FreeFormPCI104\hardware\logic\source\v5coregen\plldiv
--Design Name: plldiv
--Device: xc5vlx30t-ff665-1
--
-- Module plldiv
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.308 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.295 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.258 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT3 = 0.226 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity plldiv is
   port ( CLKIN1_IN         : in    std_logic; 
          CLKOUT0_SELECT_IN : in    std_logic; 
          CLKOUT2_SELECT_IN : in    std_logic; 
          RST_IN            : in    std_logic; 
          CLKOUT0_OUT       : out   std_logic; 
          CLKOUT1_OUT       : out   std_logic; 
          CLKOUT2_OUT       : out   std_logic; 
          CLKOUT3_OUT       : out   std_logic; 
          LOCKED_OUT        : out   std_logic);
end plldiv;

architecture BEHAVIORAL of plldiv is
   signal CLKFBOUT_CLKFBIN  : std_logic;
   signal CLKOUT0_BUF       : std_logic;
   signal CLKOUT1_BUF       : std_logic;
   signal CLKOUT2_BUF       : std_logic;
   signal CLKOUT3_BUF       : std_logic;
   signal GND_BIT           : std_logic;
   signal GND_BUS_5         : std_logic_vector (4 downto 0);
   signal GND_BUS_16        : std_logic_vector (15 downto 0);
   signal VCC_BIT           : std_logic;
begin
   GND_BIT <= '0';
   GND_BUS_5(4 downto 0) <= "00000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   CLKOUT0_BUFGMUX_CTRL_INST : BUFGMUX_CTRL
      port map (I0=>CLKOUT0_BUF,
                I1=>CLKOUT1_BUF,
                S=>CLKOUT0_SELECT_IN,
                O=>CLKOUT0_OUT);
   
   CLKOUT1_BUFG_INST : BUFG
      port map (I=>CLKOUT1_BUF,
                O=>CLKOUT1_OUT);
   
   CLKOUT2_BUFGMUX_CTRL_INST : BUFGMUX_CTRL
      port map (I0=>CLKOUT2_BUF,
                I1=>CLKOUT3_BUF,
                S=>CLKOUT2_SELECT_IN,
                O=>CLKOUT2_OUT);
   
   CLKOUT3_BUFG_INST : BUFG
      port map (I=>CLKOUT3_BUF,
                O=>CLKOUT3_OUT);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 20.000,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 40,
            CLKOUT1_DIVIDE => 32,
            CLKOUT2_DIVIDE => 16,
            CLKOUT3_DIVIDE => 8,
            CLKOUT4_DIVIDE => 8,
            CLKOUT5_DIVIDE => 8,
            CLKOUT0_PHASE => 0.000,
            CLKOUT1_PHASE => 0.000,
            CLKOUT2_PHASE => 0.000,
            CLKOUT3_PHASE => 0.000,
            CLKOUT4_PHASE => 0.000,
            CLKOUT5_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            CLKOUT1_DUTY_CYCLE => 0.500,
            CLKOUT2_DUTY_CYCLE => 0.500,
            CLKOUT3_DUTY_CYCLE => 0.500,
            CLKOUT4_DUTY_CYCLE => 0.500,
            CLKOUT5_DUTY_CYCLE => 0.500,
            COMPENSATION => "SYSTEM_SYNCHRONOUS",
            DIVCLK_DIVIDE => 1,
            CLKFBOUT_MULT => 8,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.005000)
      port map (CLKFBIN=>CLKFBOUT_CLKFBIN,
                CLKINSEL=>VCC_BIT,
                CLKIN1=>CLKIN1_IN,
                CLKIN2=>GND_BIT,
                DADDR(4 downto 0)=>GND_BUS_5(4 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                REL=>GND_BIT,
                RST=>RST_IN,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_CLKFBIN,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>CLKOUT1_BUF,
                CLKOUT2=>CLKOUT2_BUF,
                CLKOUT3=>CLKOUT3_BUF,
                CLKOUT4=>open,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>LOCKED_OUT);
   
end BEHAVIORAL;


