   
################################################################################
##$Date: 2007/08/01 23:10:49 $
##$RCSfile: example_sim_do.ejava,v $
##$Revision: 1.1.2.1 $
################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.7
##  \   \         Application : GTP Wizard 
##  /   /         Filename : example_sim.do
## /___/   /\     Timestamp : 02/08/2005 09:12:43
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script EXAMPLE_SIM.DO
## Generated by Xilinx GTP Wizard


##***************************** Beginning of Script ***************************
        
## If MTI_LIBS is defined, map unisim and simprim directories using MTI_LIBS
## This mode of mapping the unisims libraries is provided for backward 
## compatibility with previous wizard releases. If you don't set MTI_LIBS
## the unisim libraries will be loaded from the paths set up by compxlib in
## your modelsim.ini file

set XILINX   $env(XILINX)
if [info exists env(MTI_LIBS)] {    
    set MTI_LIBS $env(MTI_LIBS)
    vlib UNISIM
    vmap UNISIM $MTI_LIBS/unisim
   
}

puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
puts "Create and map work directory"
vlib work
vmap work work

puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
puts "CTI Modules"
vcom -explicit  -93 "../../../common/ctiUtil.vhd"
vcom -explicit  -93 "../../../common/ctiSim.vhd"
vcom -explicit  -93 "../../../common/txt_util.vhd"

puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
puts "MGT Wrapper"
vcom -93 -work work  ../src/pciegtp_wrapper_tile.vhd;
vcom -93 -work work  ../src/pciegtp_wrapper.vhd;

puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
puts "Example Design modules"
vcom -93 -work work  ../example/frame_gen.vhd;
vcom -93 -work work  ../example/frame_check.vhd;
vcom -93 -work work  ../example/example_mgt_top.vhd;
vcom -93 -work work  ../testbench/example_tb.vhd;

puts "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
puts "Other modules"
vcom -93 -work work ../testbench/sim_reset_mgt_model.vhd;
